from semantic_router import Route
from semantic_router.routers import SemanticRouter
from semantic_router.encoders import HuggingFaceEncoder

faq = Route(
    name="faq",
    utterances=[
        "How can I track my order?",
        "Where is my order?",
        "How long does delivery take?",
        "What is the return policy?",
        "How do I return a damaged product?",
        "How can I cancel my order?",
        "My payment failed, what should I do?",
        "Do you offer cash on delivery?",
        "Is there a warranty on electronic items?",
        "How do I use a coupon code?",
        "Can I change my shipping address after ordering?",
        "Do you ship internationally?",
        "What is your refund process?",
        "How do I contact customer support?",
        "Do you have gift cards?",
        "How do I reset my password?",
        "Where can I find my order history?",
        "Can I track multiple orders?",
        "What are your delivery charges?",
        "Do you provide invoices for purchases?",
        "Are my payment details secure?",
        "What happens if I receive the wrong item?",
        "How do I report a damaged shipment?",
        "Do you offer installation service?",
        "How long does a refund take?",
        "Can I exchange an item I bought?",
        "Are sale items returnable?",
        "What are your business hours for support?",
        "How to check warranty status?",
        "Can I schedule a delivery date?",
        "How do I update my billing information?",
        "Is same-day delivery available?",
        "How to apply for a seller refund?",
        "What documents are needed for returns?",
        "How to submit feedback about a product?",
        "Can I request a price adjustment?",
        "Where can I find product manuals?",
        "Do you provide assembly instructions?",
        "How to redeem loyalty points?",
        "Can I buy extended warranty?",
        "What payment methods do you accept?",
        "Can I save items to a wishlist?",
        "How to unsubscribe from emails?"])

sql = Route(
    name="sql",
    utterances=[
        "laptops under 50000",
        "show me gaming laptops",
        "best phones under 20000",
        "mobile phones under ₹15000",
        "find red sneakers",
        "running shoes size 10",
        "women sandals under 1000",
        "men's jackets on sale",
        "show me apple watch alternatives",
        "compare iphone and samsung phones",
        "wireless bluetooth speakers",
        "headphones with noise cancellation",
        "kitchen mixer grinder",
        "washing machine front load under 30000",
        "tiny home tv 32 inch",
        "smart tv under 25000",
        "cheap power banks",
        "fast chargers for OnePlus",
        "usb c cables",
        "backpacks for women",
        "school bags for kids",
        "gaming keyboards under 3000",
        "mechanical keyboards",
        "ssd 1tb internal",
        "external hard drive 2tb",
        "best deals on refrigerators",
        "air conditioners with inverter",
        "portable air cooler",
        "find iphones with 128gb",
        "show me airpods",
        "camera with 4k video",
        "dslr cameras for beginners",
        "kid toys under500",
        "lego sets for age 8",
        "search jeans for men",
        "find cotton kurtis",
        "sports shoes under 4000",
        "show women necklaces",
        "find perfumes for men",
        "best bluetooth earphones under 2000",
        "show me nike shoes under 5000",
        "best graphics cards",
        "gpu for pc gaming",
        "show me winter jackets",
        "smartwatches under 5000",
        "camera tripod",
        "baby stroller foldable",
        "diapers pack large size",
        "organic face wash",
        "compare lg and samsung washing machines",
        "search for cheap earbuds",
        "show budget laptops",
        "best budget phones",
        "outdoor waterproof speakers",
        "find fitness trackers",
        "find sunglasses for men",
        "find sunglasses for women",
        "perfumes",
        "shoes",
        "sneakers",
        "laptops",
        "smartphones",
        "headphones",
        "watches",
        "backpacks",
        "jackets",
        "t-shirts",
        "jeans",
        "dresses",
        "gaming consoles",
        "tablets",
        "monitors",
        "printers",
        "routers",
        "projectors",
        "speakers",
        "earbuds",
        "chargers",
        "power banks",
        "fitness bands",
        "home appliances",
        "plates",
        "lego toys",
        "action figures",
        "board games",
        "puzzles",
        "dolls",
        "kitchen utensils",
        "cookware sets",
        "blenders",
        "microwaves",
        "toasters",
        "coffee makers",
        "vacuum cleaners",
        "beauty products",
        "skincare items",
        "hair care products",
        "makeup products",
        "fragrances",
        "mobile chargers",
        "laptop chargers",
        "mouse",
        "chocolates",
        "gift items",
        "home decor",
        "diary milk",
        "show me products",
        "search products",
        "find items",
        "best deals",
        "cheap products",
        "latest products",
        "buy online",
        "shop now",
        "budget laptops",
        "gaming laptops",
        "best laptops for students",
        "mobile phones under 20000",
        "iphone",
        "samsung phones",
        "android phones",
        "ipad",
        "wireless headphones",
        "bluetooth earphones",
        "best earbuds under 2000",
        "airpods",
        "bluetooth speakers",
        "noise cancelling headphones",
        "gaming headphones",
        "smart watches",
        "apple watch alternatives",
        "keyboard",
        "gaming keyboard under 3000",
        "wireless mouse",
        "ssd",
        "1tb ssd",
        "external hard drive",
        "pendrive",
        "usb c cable",
        "laptop charger",
        "mobile charger",
        "power bank",
        "fast charger",
        "men shirts",
        "men t shirts",
        "men jeans",
        "men shoes",
        "men sneakers",
        "sports shoes for men",
        "men jackets",
        "winter jackets for men",
        "men perfumes",
        "women dresses",
        "women tops",
        "women kurtis",
        "cotton kurtis",
        "women sandals",
        "women shoes",
        "women handbags",
        "women necklaces",
        "women perfumes",
        "kids toys",
        "toys under 500",
        "lego sets",
        "lego toys for kids",
        "washing machine",
        "front load washing machine",
        "refrigerator",
        "microwave oven",
        "mixer grinder",
        "blender",
        "vacuum cleaner",
        "coffee maker",
        "air conditioner",
        "air cooler",
        "cookware set",
        "wall decor",
        "table lamps",
        "bedsheets",
        "curtains",
        "gaming console",
        "playstation",
        "xbox",
        "gaming mouse",
        "graphics card",
        "gpu for gaming",
        "skincare products",
        "face wash",
        "chocolate",
        "dairy milk",
        "dairy milk chocolate",
        "cadbury chocolate",
        "gift chocolates",
        "snacks",
        "birthday gifts",
        "anniversary gifts",
        "gift hampers",
        "diary",
        "notebook",
        "compare iphone and samsung",
        "best phone under 30000",
        "best laptop for work",
        "best headphones",
        "best smartwatch",
        "buy products",
        "shop online",
        "discount offers",
        "iphone 13",
        "iphone 14",
        "iphone 15",
        "samsung galaxy",
        "samsung galaxy s series",
        "oneplus phones",
        "redmi phones",
        "realme phones",
        "vivo phones",
        "oppo phones",
        "google pixel",
        "motorola phones",
        "hp laptops",
        "dell laptops",
        "lenovo laptops",
        "asus laptops",
        "acer laptops",
        "apple macbook",
        "macbook air",
        "macbook pro",
        "budget laptops under 50000",
        "boat headphones",
        "boat earphones",
        "jbl speakers",
        "sony headphones",
        "sony earbuds",
        "bose headphones",
        "wireless earbuds under 2000",
        "apple airpods",
        "apple watch",
        "samsung smartwatch",
        "noise smartwatch",
        "fire boltt smartwatch",
        "boat smartwatch",
        "mi band",
        "logitech mouse",
        "logitech keyboard",
        "hp keyboard",
        "dell mouse",
        "corsair keyboard",
        "samsung ssd",
        "wd hard drive",
        "seagate external hard drive",
        "sandisk pendrive",
        "anker charger",
        "anker power bank",
        "mi power bank",
        "nike shoes",
        "adidas shoes",
        "puma shoes",
        "reebok shoes",
        "woodland shoes",
        "levis jeans",
        "lee jeans",
        "us polo shirts",
        "peter england shirts",
        "raymond suits",
        "wildcraft jackets",
        "biba kurtis",
        "w kurtis",
        "libas kurtis",
        "zara dresses",
        "hm dresses",
        "only dresses",
        "allen solly women",
        "louis philippe women",
        "fossil watches for women",
        "hot wheels",
        "barbie dolls",
        "nerf guns",
        "firstcry toys",
        "lg washing machine",
        "samsung washing machine",
        "whirlpool washing machine",
        "bosch washing machine",
        "lg refrigerator",
        "samsung refrigerator",
        "haier refrigerator",
        "ifb washing machine",
        "philips mixer grinder",
        "prestige cooker",
        "pigeon cookware",
        "bajaj mixer",
        "lg air conditioner",
        "voltas ac",
        "daikin ac",
        "blue star ac",
        "carrier ac",
        "air cooler symphony",
        "lakme makeup",
        "maybelline makeup",
        "loreal shampoo",
        "dove shampoo",
        "tresemme shampoo",
        "nivea face wash",
        "ponds face cream",
        "the derma co",
        "plum skincare",
        "mamaearth products",
        "cadbury dairy milk",
        "cadbury chocolates",
        "kitkat chocolate",
        "perk chocolate",
        "nestle chocolates",
        "ferrero rocher",
        "hersheys chocolate",
        "ps5",
        "xbox series x",
        "xbox series s",
        "nintendo switch",
        "logitech gaming mouse",
        "razer keyboard",
        "nvidia graphics card",
        "amd graphics card",
        "fossil watches",
        "titan watches",
        "casio watches",
        "birthday gift",
        "anniversary gift",
        "samsung tablet",
        "lenovo tablet",
        "desktop computers",
        "all in one pc",
        "monitor",
        "lg monitor",
        "samsung monitor",
        "printer",
        "hp printer",
        "canon printer",
        "router",
        "tp link router",
        "convection microwave",
        "lg ac",
        "pressure cooker",
        "dry fruits",
        "nvidia gpu",
        "amd gpu",
        "gym equipment",
        "home gym",
        "gym products",
        "fitness equipment",
        "workout equipment",
        "dumbbells",
        "adjustable dumbbells",
        "cricket bats",
        "football",
        "basketball",
        "volleyball",
        "tennis racket",
        "badminton racket",
        "table tennis racket",
        "ping pong racket",
        "squash racket",
        "badminton net",
        "table tennis net",
        "gym bench",
        "gym rack",
        "balls",
        "gym dumbbells",
        "barbell",
        "weight plates",
        "kettlebell",
        "resistance bands",
        "pull up bar",
        "power rack",
        "bench press",
        "incline bench",
        "treadmill",
        "exercise bike",
        "stationary cycle",
        "spin bike",
        "cross trainer",
        "elliptical trainer",
        "rowing machine",
        "yoga mat",
        "exercise mat",
        "skipping rope",
        "jump rope",
        "hand gripper",
        "ab roller",
        "foam roller",
        "push up bars",
        "gym gloves",
        "weight lifting belt",
        "gym bag",
        "gym t shirts",
        "workout clothes",
        "gym leggings",
        "gym shorts",
        "sports bra",
        "running shoes",
        "training shoes",
        "protein powder",
        "whey protein",
        "mass gainer",
        "pre workout supplement",
        "bcaa supplement",
        "creatine",
        "fitness shaker bottle",
        "cultfit equipment",
        "decathlon gym equipment",
        "boldfit fitness",
        "aurion dumbbells",
        "hrx workout wear",
        "nike training shoes",
        "adidas running shoes",
        "puma training shoes",
        "garnier facewash",
        "loreal facewash",
        "nivea facewash",
        "dove facewash"
    ]
)


encoder = HuggingFaceEncoder(name="sentence-transformers/all-mpnet-base-v2")
routing = SemanticRouter(
        routes=[faq, sql],
        encoder=encoder,
        auto_sync="local"
)

    